import gsipn as pn

def createChannel(id,net,params):
	net.add_place('w'+str(id),1)
	net.add_place('d'+str(id),0)
	net.add_place('r'+str(id),0)
	net.add_place('u'+str(id),0)
	net.add_place('ur'+str(id),0)
	net.add_transition('t0_'+str(id),t_class='exp',rate=params['lambda_dd']*(1.0-params['beta']),assertion='c'+str(id)+' = not c'+str(id))
	net.add_transition('t1_'+str(id),predicate='r>0',assertion='r-=1')
	net.add_transition('t2_'+str(id),t_class='exp',rate=params['mu_dd'],assertion='r+=1\nc'+str(id)+' = not c'+str(id))
	net.add_transition('t3_'+str(id),t_class='exp',rate=params['lambda_du'],assertion='c'+str(id)+' = not c'+str(id))
	net.add_transition('t4_'+str(id),predicate='r>0',assertion='r-=1')
	net.add_transition('t5_'+str(id),t_class='exp',rate=params['mu_du'],assertion='r+=1\nc'+str(id)+' = not c'+str(id))
	net.add_transition('t6_'+str(id),predicate='ccf',assertion='c'+str(id)+' = not c'+str(id)+'\nccf'+str(id)+'= True')
	net.add_inArc('w'+str(id),'t0_'+str(id))
	net.add_outArc('d'+str(id),'t0_'+str(id))
	net.add_inArc('d'+str(id),'t1_'+str(id))
	net.add_outArc('r'+str(id),'t1_'+str(id))
	net.add_inArc('r'+str(id),'t2_'+str(id))
	net.add_outArc('w'+str(id),'t2_'+str(id))
	net.add_inArc('w'+str(id),'t3_'+str(id))
	net.add_outArc('u'+str(id),'t3_'+str(id))
	net.add_inArc('u'+str(id),'t4_'+str(id))
	net.add_outArc('ur'+str(id),'t4_'+str(id))
	net.add_inArc('ur'+str(id),'t5_'+str(id))
	net.add_outArc('w'+str(id),'t5_'+str(id))
	net.add_inArc('w'+str(id),'t6_'+str(id))
	net.add_outArc('d'+str(id),'t6_'+str(id))
	net.add_varible('ccf'+str(id),False)
	net.add_varible('c'+str(id),True)
	return net


def create1oo1(params):
	net = pn.GSIPN()
	net.add_place('w',1)
	net.add_place('d',0)
	net.add_place('r',0)
	net.add_place('u',0)
	net.add_place('ru',0)
	net.add_place('A',1)
	net.add_place('U',0)
	net.add_transition('t0',t_class='exp',rate=params['lambda_dd'],assertion='c = not c')
	net.add_transition('t1',predicate='r>0',assertion='r-=1')
	net.add_transition('t2',t_class='exp',rate=params['mu_dd'],assertion='r+=1\nc = not c')
	net.add_transition('t3',t_class='exp',rate=params['lambda_du'],assertion='c = not c')
	net.add_transition('t4',predicate='r>0',assertion='r-=1')
	net.add_transition('t5',t_class='exp',rate=params['mu_du'],assertion='r+=1\nc = not c')
	net.add_transition('t6',t_class='exp',rate=params['lambda_de'], predicate = 'not c')
	net.add_transition('t7',t_class='exp',rate=params['mu_de'],predicate = 'c')
	net.add_inArc('w','t0')
	net.add_outArc('d','t0')
	net.add_inArc('d','t1')
	net.add_outArc('r','t1')
	net.add_inArc('r','t2')
	net.add_outArc('w','t2')
	net.add_inArc('w','t3')
	net.add_outArc('u','t3')
	net.add_inArc('u','t4')
	net.add_outArc('ru','t4')
	net.add_inArc('ru','t5')
	net.add_outArc('w','t5')
	net.add_inArc('A','t6')
	net.add_outArc('U','t6')
	net.add_inArc('U','t7')
	net.add_outArc('A','t7')
	net.add_varible('c',True)
	net.add_varible('r',1)
	return net

def create1oo2(params):
	net = pn.GSIPN()
	net = createChannel(1,net,params)
	net = createChannel(2,net,params)
	net.add_place('A',1)
	net.add_place('U',0)
	net.add_place('NCCF',1)
	net.add_place('CCF',0)
	net.add_transition('t1',t_class='exp',rate=params['lambda_de'], predicate = 'not (c1 or c2)')
	net.add_transition('t2',t_class='exp',rate=params['mu_de'],predicate = 'c1 or c2')
	net.add_transition('t3',t_class='exp',rate=params['lambda_dd']*params['beta'], predicate = '(c1 and c2)', assertion = 'ccf = True')
	net.add_transition('t4',predicate = 'ccf1 and ccf2', assertion = 'ccf1=False\nccf2=False\nccf=False')
	net.add_inArc('A','t1')
	net.add_outArc('U','t1')
	net.add_inArc('U','t2')
	net.add_outArc('A','t2')
	net.add_inArc('NCCF','t3')
	net.add_outArc('CCF','t3')
	net.add_inArc('CCF','t4')
	net.add_outArc('NCCF','t4')
	net.add_varible('r',2)
	net.add_varible('ccf',False)
	return net

def create2oo3(params):
	net = pn.GSIPN()
	net = createChannel(1,net,params)
	net = createChannel(2,net,params)
	net = createChannel(3,net,params)
	net.add_place('A',1)
	net.add_place('U',0)
	net.add_place('NCCF',1)
	net.add_place('CCF',0)
	net.add_transition('t1',t_class='exp',rate=params['lambda_de'], predicate = 'not ((c1 and c2) or (c1 and c3) or (c2 and c3))')
	net.add_transition('t2',t_class='exp',rate=params['mu_de'],predicate = '(c1 and c2) or (c1 and c3) or (c2 and c3)')
	net.add_transition('t3',t_class='exp',rate=params['lambda_dd']*params['beta'], predicate = '(c1 and c2 and c3)', assertion = 'ccf = True')
	net.add_transition('t4',predicate = 'ccf1 and ccf2 and ccf3', assertion = 'ccf1=False\nccf2=False\nccf3=False\nccf=False')
	net.add_inArc('A','t1')
	net.add_outArc('U','t1')
	net.add_inArc('U','t2')
	net.add_outArc('A','t2')
	net.add_inArc('NCCF','t3')
	net.add_outArc('CCF','t3')
	net.add_inArc('CCF','t4')
	net.add_outArc('NCCF','t4')
	net.add_varible('r',3)
	net.add_varible('ccf',False)
	return net

def create242(params):
	net = pn.GSIPN()
	net = createChannel(1,net,params)
	net = createChannel(2,net,params)
	net = createChannel(3,net,params)
	net = createChannel(4,net,params)
	net = createChannel(5,net,params)
	net = createChannel(6,net,params)
	func_predicate = '(((c1 or c2 or c3) and c4) or c5 or c6)'
	neg_func_predicate = 'not (((c1 or c2 or c3) and c4) or c5 or c6)'
	ccf_predicate = 'c1 and c2 and c3 and c4 and c5 and c6'
	ccf_assertion = 'ccf1=False\nccf2=False\nccf3=False\nccf4=False\nccf5=False\nccf6=False'
	net.add_place('A',1)
	net.add_place('U',0)
	net.add_place('NCCF',1)
	net.add_place('CCF',0)
	net.add_transition('t1',t_class='exp',rate=params['lambda_de'], predicate = neg_func_predicate)
	net.add_transition('t2',t_class='exp',rate=params['mu_de'],predicate = func_predicate)
	net.add_transition('t3',t_class='exp',rate=params['lambda_dd']*params['beta'], predicate = ccf_predicate, assertion = 'ccf = True')
	net.add_transition('t4',predicate = ccf_predicate, assertion = ccf_assertion)
	net.add_inArc('A','t1')
	net.add_outArc('U','t1')
	net.add_inArc('U','t2')
	net.add_outArc('A','t2')
	net.add_inArc('NCCF','t3')
	net.add_outArc('CCF','t3')
	net.add_inArc('CCF','t4')
	net.add_outArc('NCCF','t4')
	net.add_varible('r',8)
	net.add_varible('ccf',False)
	return net

